In [1]:
from numpy import *

In [19]:
def cost(m,c):
    # compute two distance ,row is data, coloum is for medoid
    distanceMatrix = zeros((m.shape[0],c.shape[0]))
    for i in range(c.shape[0]):
        distanceMatrix[:,i] = sum(abs(m - c[i,:]),axis= 1)
    costMatrix = amin(distanceMatrix,axis = 1)
#     print(costMatrix)
    return costMatrix

In [49]:
trainData = array([[0,0],[0,1],[2,2],[3,3],[4,2]])
# random choise 2 medoids to initialize
idx = random.randint(5, size=2)
print(idx)
medoids = trainData[idx,:]
print(medoids)
print(cost(trainData,medoids))
costall = sum(cost(trainData,medoids))
costall

[0 4]
[[0 0]
 [4 2]]
[ 0.  1.  2.  2.  0.]


5.0

In [48]:
while True:
    isStable = True
    for m in range(medoids.shape[0]):
        for t in range(trainData.shape[0]):
    #         only consider non-medoid
            if trainData[t,:] not in medoids:
                # switch medoid
                nowMedoid = medoids[m,:]
                medoids[m,:] = trainData[t,:]
                coatall_tmp = sum(cost(trainData,medoids))
                print(medoids)
                print(cost(trainData,medoids))
                print(costall)
                if coatall_tmp < costall :
                    # it is a good exchange
                    costall = coatall_tmp
                    isStable = False
                    print("change")
                else :
                    # is not a good exchange ,now exchange it back
                    medoids[m,:] = nowMedoid
                    print("undo change")
    if isStable :
        break

print(costall)
print(medoids)

[[0 0]
 [3 3]]
[ 0.  1.  2.  0.  2.]
13.0
change
[[2 2]
 [3 3]]
[ 4.  3.  0.  0.  2.]
5.0
undo change
[[2 2]
 [0 0]]
[ 0.  1.  0.  2.  2.]
5.0
undo change
[[2 2]
 [3 3]]
[ 4.  3.  0.  0.  2.]
5.0
undo change
[[0 0]
 [3 3]]
[ 0.  1.  2.  0.  2.]
5.0
undo change
[[2 2]
 [3 3]]
[ 4.  3.  0.  0.  2.]
5.0
undo change
[[2 2]
 [0 0]]
[ 0.  1.  0.  2.  2.]
5.0
undo change
[[2 2]
 [3 3]]
[ 4.  3.  0.  0.  2.]
5.0
undo change
5.0
[[2 2]
 [3 3]]
